### ISSUE TITLE
How to detect point on border as insided one.

### ISSUE THREAD

**Issue by joonhwan** [snatik/polygon-contains-point#12]
For a given rect like

(-1, -1), (-1, 1), (1, 1), (1, -1) 

the point (0,1) is not detected as inside of polygon.
How to detect it as insid of polygon?

**Comment by sromku** [comment]
The used algorithm here is [Ray casting algorithm](https://en.wikipedia.org/wiki/Point_in_polygon#Ray_casting_algorithm). If the test point is on the border of the polygon, this algorithm will deliver unpredictable results; i.e. the result may be “inside” or “outside”. In general it depends on ray creation with respect to the coordinate system.

> **[From wiki](https://en.wikipedia.org/wiki/Point_in_polygon)**:
> Unfortunately, this method won't work if the point is on the edge of the polygon.

For example, in polygon `(-1, -1), (-1, 1), (1, 1), (1, -1)`:

- This is outside:  (0,1)
- This is inside: (-1,0)

**Comment by sromku** [comment]
You can see the new added test to showcase this issue. https://github.com/snatik/polygon-contains-point/commit/e5717ff09c320c842f3a8a9ef62e52bafd61982c
