### ISSUE TITLE
Tag a release

### ISSUE THREAD

**Issue by Goutte** [snatik/polygon-contains-point#4]
Could you please tag a [release](https://github.com/sromku/polygon-contains-point/releases) so as to make inclusion in projects easier ?

Or, even better, add it to maven or jcenter ?

This is a good lib, and I don't want to ruin it by copying the files directly into my project.

**Comment by sromku** [comment]
@Goutte It's about time, right ;)

Tagged and added the updated version **1.0.2** to releases. Check it out - https://github.com/snatik/polygon-contains-point/releases/latest
